import test from "node:test";
import assert from "node:assert/strict";
import {
    buildFlangeDrawing,
    serializeSvgVectorDocument,
    SVG_VECTOR_DOCUMENT_SCHEMA_VERSION,
    validateSvgVectorDocument,
    type FlangeLookupResponse,
} from "./engine/index.ts";

const response: FlangeLookupResponse = {
    count: { value: 4 },
    boltSize: "M16",
    measures: {
        D: { value: 165 },
        K: { value: 125 },
        L: { value: 18 },
        C1: { value: 18 },
        B1: { value: 100 },
    },
};

test("validates vector documents generated by the flange drawing engine", () => {
    const document = buildFlangeDrawing({
        flangeType: "01",
        face: null,
        response,
    });
    const result = validateSvgVectorDocument(document);

    assert.equal(document.schemaVersion, SVG_VECTOR_DOCUMENT_SCHEMA_VERSION);
    assert.equal(result.isValid, true);
    assert.deepEqual(result.errors, []);
    assert.match(serializeSvgVectorDocument(document), /^<svg/);
});

test("validates JSON round-tripped vector documents", () => {
    const document = buildFlangeDrawing({
        flangeType: "99",
        face: null,
        response,
    });
    const parsedDocument: unknown = JSON.parse(JSON.stringify(document));
    const result = validateSvgVectorDocument(parsedDocument);

    assert.equal(result.isValid, true);
    assert.deepEqual(result.errors, []);
});

test("rejects vector documents with missing bounds", () => {
    const result = validateSvgVectorDocument({
        schemaVersion: SVG_VECTOR_DOCUMENT_SCHEMA_VERSION,
        elements: [],
    });

    assert.equal(result.isValid, false);
    assert.ok(result.errors.includes("bounds must be an object"));
});

test("rejects vector documents with missing required element fields", () => {
    const result = validateSvgVectorDocument({
        schemaVersion: SVG_VECTOR_DOCUMENT_SCHEMA_VERSION,
        bounds: {
            minX: 0,
            minY: 0,
            width: 100,
            height: 100,
        },
        elements: [
            { kind: "line", x1: 0, y1: 0, x2: 10 },
            { kind: "path" },
            { kind: "text", x: 0, text: "missing y" },
        ],
    });

    assert.equal(result.isValid, false);
    assert.ok(result.errors.includes("elements[0].y2 must be a finite number"));
    assert.ok(result.errors.includes("elements[1].d must be a non-empty string"));
    assert.ok(result.errors.includes("elements[2].y must be a finite number"));
});

test("rejects vector documents with unsupported element kinds and schema versions", () => {
    const result = validateSvgVectorDocument({
        schemaVersion: "2.0",
        bounds: {
            minX: 0,
            minY: 0,
            width: 100,
            height: 100,
        },
        elements: [
            { kind: "circle", cx: 10, cy: 10, r: 5 },
        ],
    });

    assert.equal(result.isValid, false);
    assert.ok(result.errors.includes("schemaVersion must be 1.0"));
    assert.ok(result.errors.includes("elements[0].kind is not supported"));
});
